Pizzaria-G11/Controllers/PizzasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzariaAtv.Models.ViewModels.Request;
using PizzariAtv.Data;
using PizzariAtv.Models;
using PizzariAtv.Models.ViewModels.Responsive;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PizzariAtv.Controllers
{
    public class PizzasController : Controller
    {
        private PizzariaDbContext _context;

        public PizzasController(PizzariaDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Pizzas);
        }
        public IActionResult Detalhes(int id)
        {
            var result = _context.Pizzas
                .Include(t => t.Tamanho)
                .Include(ps => ps.PizzasSabores).ThenInclude(c => c.Sabor)
                .FirstOrDefault(p => p.Id == id);
            GetPizzasDTO pizzasDTO = new GetPizzasDTO()
            {
                Nome = result.Nome,
                Descricao = result.Descricao,
                ImagemURL = result.ImagemURL,
                Preco = result.Preco,
                Tamanho = result.Tamanho.Nome,
                Sabores = result.PizzasSabores.Select(x => x.Sabor.Nome).ToList()
            };
            return View(pizzasDTO);

        }
        public IActionResult Criar()
        {
            DadosDropDow();
            return View();
        }
        public void DadosDropDow()
        {
            var resp = new PostPizzaDropDown()
            {
                Sabores = _context.Sabores.OrderBy(x => x.Nome).ToList(),
                Tamanhos = _context.Tamanhos.OrderBy(x => x.Nome).ToList()
            };

            ViewBag.Sabores = new SelectList(resp.Sabores, "Id", "Nome");
            ViewBag.Tamanhos = new SelectList(resp.Tamanhos, "Id", "Nome");

        }
        [HttpPost]
        public IActionResult Criar(PostPizzaDTO pizzaDTO)
        {
            if (!ModelState.IsValid)
            {
                DadosDropDow();
                return View();
            }
            Pizza pizza = new Pizza
                (
                    pizzaDTO.Nome,
                    pizzaDTO.Descricao,
                    pizzaDTO.Preco,
                    pizzaDTO.ImagemURL,
                    pizzaDTO.TamanhoId
                );
            _context.Add(pizza);
            _context.SaveChanges();
            foreach (var sabor in pizzaDTO.SaboresId)
            {
                int? saborId = _context.Sabores.Where(c => c.Id == sabor).FirstOrDefault().Id;

                if (saborId != null)
                {
                    var novoSabor = new PizzasSabores(pizza.Id, saborId.Value);
                    _context.PizzasSabores.Add(novoSabor);
                    _context.SaveChanges();
                }
            }
            
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Atualizar(int id)
        {
            var result = _context.Pizzas.Include(x => x.PizzasSabores).ThenInclude(x => x.Sabor)
                                        .FirstOrDefault(x => x.Id == id);
            if (result == null) return View("NotFound");
            var resp = new PostPizzaDTO()
            {
                Nome = result.Nome,
                Descricao = result.Descricao,
                Preco = result.Preco,
                ImagemURL = result.ImagemURL,
                TamanhoId = result.TamanhoId,
                SaboresId = result.PizzasSabores.Select(x => x.SaborId).ToList()
            };
            DadosDropDow();
            return View(resp);
        }
        [HttpPost]
        public IActionResult Atualizar(int id, PostPizzaDTO pizzaDTO)
        {
            var result = _context.Pizzas.FirstOrDefault(x => x.Id == id);
            if (!ModelState.IsValid) return View(result);
            result.AtualizarDados(pizzaDTO.Nome, pizzaDTO.Descricao, pizzaDTO.Preco, pizzaDTO.ImagemURL);
            _context.Update(result);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Deletar(int id)  
        {
            var remove = _context.Pizzas.FirstOrDefault(x => x.Id == id);
            if (remove == null) return View("NotFound");
            return RedirectToAction(nameof(Index));
        }
        [HttpPost,ActionName("Deletar")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var remove = _context.Pizzas.FirstOrDefault(x => x.Id == id);
            if (remove == null) return View("NotFound");
            _context.Remove(remove);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Pizzaria-G11/Controllers/SaboresController.cs
using Microsoft.AspNetCore.Mvc;
using PizzariaAtv.Models.ViewModels.Request;
using PizzariAtv.Data;
using PizzariAtv.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PizzariAtv.Controllers
{
    public class SaboresController : Controller
    {
        private PizzariaDbContext _context;

        public SaboresController(PizzariaDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Sabores);
        }
        public IActionResult Detalhes(int id)
        {
            return View(_context.Sabores.Find(id));

        }
        public IActionResult Criar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Criar(PostSaborDTO saborDTO)
        {
            if (!ModelState.IsValid) { return View(); }

            Sabor sabor = new Sabor
            (
                saborDTO.Nome,
                saborDTO.Descricao,
                saborDTO.ImagemURL
            );
            _context.Sabores.Add(sabor);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Atualizar(int id)
        {
            var result = _context.Sabores.FirstOrDefault(x => x.Id == id);
            if (result == null) return View("NotFound");
            var resp = new PostSaborDTO()
            {
                Nome = result.Nome,
                Descricao = result.Descricao,
                ImagemURL = result.ImagemURL
                
            };
            return View(resp);
        }
        [HttpPost]
        public IActionResult Atualizar(int id, PostSaborDTO saborDTO)
        {
            var result = _context.Sabores.FirstOrDefault(x => x.Id == id);
            if (!ModelState.IsValid) return View(result);
            result.AtualizarDados(saborDTO.Nome, saborDTO.Descricao,saborDTO.ImagemURL);
            _context.Update(result);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Deletar(int id)
        {
            var remove = _context.Sabores.FirstOrDefault(x => x.Id == id);
            if (remove == null) return View("NotFound");
            return RedirectToAction(nameof(Index));
        }
        [HttpPost, ActionName("Deletar")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var remove = _context.Sabores.FirstOrDefault(x => x.Id == id);
            if (remove == null) return View("NotFound");
            _context.Remove(remove);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Pizzaria-G11/Controllers/TamanhosController.cs
using Microsoft.AspNetCore.Mvc;
using PizzariaAtv.Models.ViewModels.Request;
using PizzariAtv.Data;
using PizzariAtv.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PizzariAtv.Controllers
{
    public class TamanhosController : Controller
    {
        private PizzariaDbContext _context;

        public TamanhosController(PizzariaDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Tamanhos);
        }
        public IActionResult Detalhes(int id)
        {
            return View(_context.Tamanhos.Find(id));

        }
        public IActionResult Criar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Criar(PostTamanhoDTO tamanhoDTO)
        {
            if (!ModelState.IsValid) { return View(); }

            Tamanho tamanho = new Tamanho
            (
                tamanhoDTO.Nome,
                tamanhoDTO.Pedacos,
                tamanhoDTO.Descricao
            );
            _context.Tamanhos.Add(tamanho);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Atualizar(int id)
        {
            var result = _context.Sabores.FirstOrDefault(x => x.Id == id);
            if (result == null) return View("NotFound");
            var resp = new PostSaborDTO()
            {
                Nome = result.Nome,
                Descricao = result.Descricao,
                ImagemURL = result.ImagemURL

            };
            return View(resp);
        }
        [HttpPost]
        public IActionResult Atualizar(int id, PostTamanhoDTO tamanhoDTO)
        {
            var result = _context.Tamanhos.FirstOrDefault(x => x.Id == id);
            if (!ModelState.IsValid) return View(result);
            result.AtualizarDados(tamanhoDTO.Nome,tamanhoDTO.Pedacos,tamanhoDTO.Descricao);
            _context.Update(result);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Deletar(int id)
        {
            var remove = _context.Tamanhos.FirstOrDefault(x => x.Id == id);
            if (remove == null) return View("NotFound");
            return RedirectToAction(nameof(Index));
        }
        [HttpPost, ActionName("Deletar")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var remove = _context.Tamanhos.FirstOrDefault(x => x.Id == id);
            if (remove == null) return View("NotFound");
            _context.Remove(remove);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Pizzaria-G11/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzariAtv</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pizzas" asp-action="Index">PizzariAtv</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizzas" asp-action="Index">Pizzas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tamanhos" asp-action="Index">Tamanhos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sabores" asp-action="Index"> Sabores</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PizzariAtv - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>